[package]
name = "zksync-web3-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0.4", features = ["rustls"] }
tokio = { version = "1", features = ["macros", "process"] }
clap = { version = "4.2.7", features = ["derive"] }

# Serialization
serde = "1.0.163"
serde_json = { vesion = "1" }
hex = "0.4"

# Error handling
eyre = "0.6" # CLI error handling
thiserror = "1.0.40" # Library error handling

# Logging
log = "0.4"
env_logger = "0.10"
